name: Digital Ocean Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Update files
        uses: appleboy/ssh-action@master
        env:
          DEPLOYPATH: "/var/www/davidgarxa.com/public_html/drilling-mud-mex/"
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: DEPLOYPATH
          script: |
            cd repositories/Drilling-Mud-Mex
            git pull origin
            echo "Update repo"
            echo "$DEPLOYPATH"
            cp *.html $DEPLOYPATH
            cp style.css $DEPLOYPATH
            cp -R images/ $DEPLOYPATH
            cp script.js $DEPLOYPATH
